from fastapi import FastAPI, Request, status
from fastapi.responses import JSONResponse

from exceptions.exceptions import (
    BaseOrbitalError,
    DatabaseError,
    InvalidArgumentError,
    InvalidStateError,
    NotFoundError,
    ServiceError,
    SunPositionError,
    UnauthorizedError,
    UnknownError,
)

STATUS_MAP: dict[type[BaseOrbitalError], int] = {
    ServiceError: status.HTTP_400_BAD_REQUEST,
    NotFoundError: status.HTTP_404_NOT_FOUND,
    InvalidArgumentError: status.HTTP_422_UNPROCESSABLE_ENTITY,
    InvalidStateError: status.HTTP_409_CONFLICT,
    DatabaseError: status.HTTP_400_BAD_REQUEST,
    UnauthorizedError: status.HTTP_401_UNAUTHORIZED,
    SunPositionError: status.HTTP_500_INTERNAL_SERVER_ERROR,
    UnknownError: status.HTTP_500_INTERNAL_SERVER_ERROR,
}


def setup_exception_handlers(app: FastAPI) -> None:
    """Adds exception handlers to the app"""

    @app.exception_handler(BaseOrbitalError)
    async def base_orbital_error_handler(request: Request, exc: BaseOrbitalError) -> JSONResponse:
        """Handles custom exceptions (BaseOrbitalError child classes) generated by the backend"""
        return JSONResponse(
            status_code=STATUS_MAP.get(type(exc), status.HTTP_500_INTERNAL_SERVER_ERROR),
            content={"message": exc.message},
        )
