services:
  api:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ../..
      dockerfile: scripts/dev/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ../../backend:/app/backend
    env_file:
      - ../../.env
    environment:
      - PYTHONPATH=/app/backend
      - GS_DATABASE_LOCATION=host.docker.internal
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    entrypoint: ["/bin/bash", "-c"]
    command:
    - |
      /opt/keycloak/bin/kc.sh start-dev --import-realm &
      sleep 10
      /opt/keycloak/bin/kcadm.sh config credentials \
        --server http://localhost:8080 \
        --realm master \
        --user mcc-admin \
        --password uworbital
      /opt/keycloak/bin/kcadm.sh update realms/master -s sslRequired=NONE
      wait
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: mcc-admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: uworbital
    ports:
      - "8080:8080"
    volumes:
    - keycloak_data:/opt/keycloak/data
    - ../../backend/keycloak/mcc-realm.json:/opt/keycloak/data/import/mcc-realm.json
  aro-frontend:
    build:
      context: ../../frontend/aro
      dockerfile: ../../scripts/dev/Dockerfile.aro
    ports:
      - "5173:5173"
    working_dir: /app
    volumes:
      - ../../frontend/aro:/app
      - /app/node_modules
  mcc-frontend:
    build:
      context: ../../frontend/mcc
      dockerfile: ../../scripts/dev/Dockerfile.mcc
    ports:
      - "5174:5174"
    working_dir: /app
    volumes:
      - ../../frontend/mcc:/app
      - /app/node_modules
volumes:
  keycloak_data:
