"""
Update for commands pipeline

Revision ID: 1440e2851238
Revises: 6c54d182bb55
Create Date: 2026-03-23 22:31:43.396369

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1440e2851238"
down_revision = "514ae47263fe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """
    Adds a priority field along with created at field to the commands such that commands
    pipeline will work.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("commands", sa.Column("priority", sa.Integer(), nullable=False, server_default="0"), schema="main")
    op.add_column(
        "commands",
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        schema="transactional",
    )

    # Manually added: Use autocommit for this operation as ALTER TYPE ADD VALUE cannot run in a transaction
    op.execute("ALTER TYPE commandstatus ADD VALUE 'PACKETED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    So that precommit will stop screaming at me.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("commands", "created_at", schema="transactional")
    op.drop_column("commands", "priority", schema="main")
    # ### end Alembic commands ###
