"""add user_id fk to commands

Revision ID: 7a08f61ca7cc
Revises: merge_001
Create Date: 2026-05-30 17:09:48.782481

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '7a08f61ca7cc'
down_revision = 'merge_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commands', sa.Column('user_id', sa.Uuid(), nullable=False), schema='transactional')
    op.create_foreign_key(None, 'commands', 'users_data', ['user_id'], ['id'], source_schema='transactional', referent_schema='mcc_users', onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commands', 'user_id', schema='transactional')
    # ### end Alembic commands ###
