"""create MCCUsers table

Revision ID: 986e5b72bde5
Revises: 6c54d182bb55
Create Date: 2026-03-07 15:12:50.726452

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '986e5b72bde5'
down_revision = '6c54d182bb55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS mcc_users;")
    op.create_table('users_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='mcc_users'
    )
    op.create_index(op.f('ix_mcc_users_users_data_id'), 'users_data', ['id'], unique=False, schema='mcc_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcc_users_users_data_id'), table_name='users_data', schema='mcc_users')
    op.drop_table('users_data', schema='mcc_users')
    # ### end Alembic commands ###
